### PR TITLE
Port to GTK4

### LINKED ISSUE #75: Port to GTK4 ?
Thanks for your work. gtk4-layershell is already available. No idea how much effort a port from GTK3 to 4 is in this scope, but that would be nice to have imo. I might look into this.

### LINKED ISSUE #101: Top Margin is applied inconsistently on sway, and is wildly wrong with fractional scaling
SwayOSD applies the top margin very inconsistently, and it's wildly incorrectly when fractional scaling is used.

~~The `win.allocated_height()` always returns the unscaled height of the window, while `monitor.workarea().height()` always returns the (integer-) scaled height of the window.~~ (EDIT: both return unscaled heights, my bad)

The main issue appears to be that `win.allocated_height()` is often outdated/incorrect at the time the `connect_map()` event handler is called (see "Positioning Inconsistency" below).

~~The fractional scale issue could also be a compositor bug. I'm on sway-git and I don't recall having seen that issue a while ago since I've been using fractional scaling for a long time.~~ The outdated size issue is definitely a SwayOSD bug though. I'm gonna try and see what the fractional scaling issue is and find/fix the root cause, and then try to tackle the inconsistent window height issue.

EDIT: The issue also happens on `sway 1.9`, so this at least isn't a recent issue, and upon reading the `wlr-layer-shell` protocol, the compositor behaviour seems correct. However, since the margin of the layer shell window is in 'surface-local coordinates' and the surface is scaled by a potentially fractional amount, there is no way for a fractional-scaling-unaware client to accurately position itself on a specific point on the screen using margins. The only solution that I can think of that would be less badly affected by GTK not supporting fractional scaling is using a bottom anchor for all `top_margin` values greater than `0.5`.

## Positioning Inconsistency

The following screenshots were taken with the default top margin value of 0.85. One case where the previous notification displayed the same text (decrement volume twice when already at 0%), and one case where the previous notification displayed different text (increment volume and decrement again):

## Previous notification same (correct window height, 64 pixels)

swayosd-window-height-064

## Previous notification different (incorrect window height, 1 pixel)

swayosd-window-height-001

## Scale factor issues

The following screenshots were taken with the default top margin value of 0.85 and different output scale:

### Scale 1 (correct)

swayosd-scale-1

### Scale 2 (correct)

swayosd-scale-2

### Scale 1.5 (incorrect)

swayosd-scale-1 5

### Scale 1.175 (incorrect)

swayosd-scale-1 175

### PR DESCRIPTION
**Pull request by Ferdi265**
This PR ports SwayOSD to GTK4. Applies on top of #104. Fixes #75. Fixes #101.

A lot of changes to prepare for this were already done, but GTK4 changes a lot more which had to be worked around. Note that this branch requires [gtk4-layer-shell 1.0.4](https://github.com/wmww/gtk4-layer-shell/releases/tag/v1.0.4) or later due to an [issue causing Wayland protocol errors](https://github.com/wmww/gtk4-layer-shell/issues/34).

Main changes:
- syntax for `clone!` macro has changed (`#[strong]` instead of `@strong` and `,` instead of `=>`)
- GDK Display no longer has useful monitor added/removed signals
  - the alternative is to use the `.monitors()` ListModel, which is non-generic and has an ugly API. seems to work though.
- StyleContext is deprecated and its API changed
  - CSSProviders still exist, but the API looks different, I managed to make it compile, but I'm not 100% sure it's correct
- Some Widget/Container APIs changed
  - Monitor no longer has `workarea()`, switched to `geometry()`, hope that's the same.
  - Window has `set_child()` instead of `add()` 
  - Box now has `append()` instead of `add()`
    - Box no longer has a simple way of iterating through all children, which sucks
    - ~~somehow removing Box children doesn't work~~ you need to be very careful when iterating to make remove work, since it seems to be a linked-list-like structure.
  - Image no longer has a `size_allocate` signal, but `realize` is hopefully similar 
  - The logic for updating the layer shell margin was changed to (a) work properly in GTK4 and (b) work properly with output scale changes

## TODO
- [X] Make it compile
- [x] Make it work without crashing
- [x] Fix visual changes and bugs

### CODE REVIEW

**Comment by Ferdi265** [comment]
This will probably take a while to be finished, but since there is now at least a compiling gtk4 codebase, hopefully it will be less daunting for other people to help.

**Comment by Ferdi265** [comment]
Fixes #75.

**Comment by Ferdi265** [comment]
I figured out how to make it work (including a bug reproducer for gtk4-layer-shell), will push once it's cleaned up :)

**Comment by Ferdi265** [comment]
Fix for upstream gtk4-layer-shell issue: https://github.com/wmww/gtk4-layer-shell/pull/49

With that fix it doesn't crash any more. I also changed the margin code so it is always updated when its inputs changed, which is more reliable than relying on `connect_map()` and hoping everything is ready at that point and doesn't change any more. I also worked around a bug with GTK4's output scale sometimes being incorrect (it never goes back to 1.0 scale after being at 2.0 even if I change the output scale back in sway) by manually transforming the output size into window coordinates (this fixes #101).

The main issue remaining is some "Channel Send error: sending into a closed channel" errors printed on stderr, I probably did something wrong while porting the `MainContext::channel()` usage to `async_channel` (I should check whether this also happens in #104 and fix both)

**Comment by Ferdi265** [comment]
> The main issue remaining is some "Channel Send error: sending into a closed channel" errors printed on stderr, I probably did something wrong while porting the `MainContext::channel()` usage to `async_channel` (I should check whether this also happens in #104 and fix both)

Channel issue is now fixed with the latest rebase.

**Comment by Ferdi265** [comment]
Should be mostly ready for review now. It looks slightly different than the GTK3 version (GTK4 has more default padding), but looks like it works quite well. I've switched to it as my daily driver.

Still depends on the [upstream gtk4-layer-shell fix PR](https://github.com/wmww/gtk4-layer-shell/pull/49)

**Comment by werdahias** [comment]
awesome, thanks for your work !

**Comment by NullVoxPopuli** [comment]
excited for this!

**Comment by Ferdi265** [comment]
I've been running this branch as my daily driver for the last month and haven't seen any crashes, but it seems to hang sometimes, requiring a service restart to get responsive again. I'll try to run a debug build for the next week or two to see if I can figure out the issue.

**Comment by NullVoxPopuli** [comment]
This is working great -- I had to install some deps to compile it, but 10/10 would install/compile again

**Comment by Ferdi265** [comment]
The upstream gtk4-layer-shell fix for the crash issue has just been merged, but hasn't been released yet.

**Comment by Ferdi265** [comment]
> I've been running this branch as my daily driver for the last month and haven't seen any crashes, but it seems to hang sometimes, requiring a restart to get responsive again. I'll try to run a debug build for the next week or two to see if I can figure out the issue.

The libinput dbus signal listener was hanging in `Sender::send_blocking()`. This seems to happen mostly when SwayOSD is started as a systemd user service on system startup, seems like a timing issue.

I changed the code to spawn an async task on the MainContext and use an async `send().await` there instead. Let's see if this fixes the issue. If this doesn't occur in the next two weeks or so in my testing I'll consider this fixed.

**Comment by Ferdi265** [comment]
> UPDATE: I haven't seen the issue last week, so I've changed to running a release build instead of a debug build and if it still doesn't appear I consider this fixed.

The issue hasn't reappeared, and I also haven't encountered any other obvious bugs in my usage. Also, `gtk4-layer-shell` 1.0.4 has been released, which contains the fix for the upstream crash issue.

**Review by ErikReider — APPROVED** [review]
Thanks a ton for the PR! Sorry for the delay, Uni has me pretty busy 😅

**Pull request merged**
